spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bdbarbearia?createDatabaseIfNotExist=true
    username: root
    password: mcs010203

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never